kumuluzee:
  name: nakupovalni-seznami
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/NakupovalniSeznamiJDBC
      connection-url: jdbc:postgresql://localhost:5432/nakupovalniseznamidb
      username: postgres
      password: postgres
      max-pool-size: 20