kumuluzee:
  name: nakupovalni-seznami
  version: 1.0.0
  recommendation-url: http://localhost:3333/v1/priporocila
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/NakupovalniSeznamiJDBC
      connection-url: jdbc:postgresql://localhost:5432/nakupovalniseznamidb
      username: postgres
      password: postgres
      max-pool-size: 20